### ISSUE TITLE
help me out

### ISSUE THREAD

**Issue by keithsimkin** [instabotai/instabotai-webgui#3]
![Capture](https://user-images.githubusercontent.com/45896639/62428199-7cebe800-b707-11e9-8d1f-1f0bd1f7803a.PNG)

**Comment by steffanjensen** [comment]
Windows:

https://www.tensorflow.org/install/source_windows

(Opened a thread here for the devs to include tensorflow for 3.7 on windows)

https://github.com/tensorflow/tensorflow/issues/31431

**Comment by steffanjensen** [comment]
you can use python Version 3.6

**Comment by steffanjensen** [comment]
now works with python 3.7
